actions:
  SkyWalker:
    display: "SkyWalker"
    stroke: "→←→←"
    announce: "空中散歩術！"
    floor_size: 2
  WeatherClear:
    display: "WeatherClear"
    stroke: "←↑→"
    announce: "あ～した天気になれ!"
  JumpPad:
    display: "JumpPad"
    stroke: "↓↑"
    announce: "ジャンプパッド展開!"

rod_item: "BLAZE_ROD"

magic_went_off:
  announce: "魔力が暴走した。"
  damage: 4

stroke:
  degree: 12
  timer: 5
  times: 10
