name: StrokePlugin
version: 1.0-SNAPSHOT
main: net.kunmc.lab.stroke.strokeplugin.StrokePlugin
api-version: 1.15
authors: [CrewL2020]

commands:
  Stroke@Title:
    description: show title
  Stroke@ReloadConfig:
    description: reload config
  Stroke@help:
    description: show help
  Stroke@list:
    description: show command list
  Stroke@description:
    description: show explains
  Stroke@descriptionFormal:
    description: show explains detail

permissions:
  stroke.permission:
    default: op